/*Generated 2016-05-23 08:17:41.711000*/ var timezone_json = {
  "Bangladesh": [{ tzid: "Asia/Dhaka", name: "Bangladesh" }],
  "Belgium": [{ tzid: "Europe/Brussels", name: "Romance" }],
  "Burkina Faso": [{ tzid: "Africa/Abidjan", name: "Greenwich" }],
  "Bulgaria": [{ tzid: "Europe/Sofia", name: "FLE" }],
  "Bosnia & Herzegovina": [{ tzid: "Europe/Belgrade", name: "Central Europe" }],
  "Barbados": [{ tzid: "America/Barbados", name: "SA Western" }],
  "Wallis & Futuna": [{ tzid: "Pacific/Wallis", name: "UTC+12" }],
  "St Barthelemy": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "Bermuda": [{ tzid: "Atlantic/Bermuda", name: "Atlantic" }],
  "Brunei": [{ tzid: "Asia/Brunei", name: "Singapore" }],
  "Bolivia": [{ tzid: "America/La_Paz", name: "SA Western" }],
  "Japan": [{ tzid: "Asia/Tokyo", name: "Tokyo" }],
  "Burundi": [{ tzid: "Africa/Maputo", name: "South Africa" }],
  "Benin": [{ tzid: "Africa/Lagos", name: "W. Central Africa" }],
  "Bhutan": [{ tzid: "Asia/Thimphu", name: "Bangladesh" }],
  "Jamaica": [{ tzid: "America/Jamaica", name: "SA Pacific" }],
  "Jordan": [{ tzid: "Asia/Amman", name: "Jordan" }],
  "Samoa (western)": [{ tzid: "Pacific/Apia", name: "Samoa" }],
  "Caribbean NL": [{ tzid: "America/Curacao", name: "SA Western" }],
  "Brazil": [
    { tzid: "America/Noronha", name: "UTC-02" },
    { tzid: "America/Belem", name: "Belem" },
    { tzid: "America/Fortaleza", name: "Fortaleza" },
    { tzid: "America/Recife", name: "Recife" },
    { tzid: "America/Araguaina", name: "Araguaina" },
    { tzid: "America/Maceio", name: "Maceio" },
    { tzid: "America/Bahia", name: "Bahia" },
    { tzid: "America/Sao_Paulo", name: "Sao Paulo" },
    { tzid: "America/Campo_Grande", name: "Campo Grande" },
    { tzid: "America/Cuiaba", name: "Cuiaba" },
    { tzid: "America/Porto_Velho", name: "Velho" },
    { tzid: "America/Boa_Vista", name: "Boa Vista" },
    { tzid: "America/Manaus", name: "Manaus" },
    { tzid: "America/Rio_Branco", name: "Rio Branco" }
  ],
  "Bahamas": [{ tzid: "America/Nassau", name: "Eastern" }],
  "Jersey": [{ tzid: "Europe/London", name: "GMT" }],
  "Belarus": [{ tzid: "Europe/Minsk", name: "Belarus" }],
  "Belize": [{ tzid: "America/Belize", name: "Central America" }],
  "Russia": [
    { tzid: "Europe/Kaliningrad", name: "Kaliningrad" },
    { tzid: "Europe/Moscow", name: "Russian" },
    { tzid: "Europe/Simferopol", name: "Russian" },
    { tzid: "Europe/Volgograd", name: "Russian" },
    { tzid: "Europe/Samara", name: "Russia Zone 3" },
    { tzid: "Asia/Yekaterinburg", name: "Ekaterinburg" },
    { tzid: "Asia/Omsk", name: "N. Central Asia" },
    { tzid: "Asia/Novosibirsk", name: "N. Central Asia" },
    { tzid: "Asia/Novokuznetsk", name: "North Asia" },
    { tzid: "Asia/Krasnoyarsk", name: "North Asia" },
    { tzid: "Asia/Irkutsk", name: "North Asia East" },
    { tzid: "Asia/Chita", name: "Yakutsk" },
    { tzid: "Asia/Yakutsk", name: "Yakutsk" },
    { tzid: "Asia/Khandyga", name: "Yakutsk" },
    { tzid: "Asia/Vladivostok", name: "Vladivostok" },
    { tzid: "Asia/Ust-Nera", name: "Vladivostok" },
    { tzid: "Asia/Magadan", name: "Magadan" },
    { tzid: "Asia/Sakhalin", name: "Vladivostok" },
    { tzid: "Asia/Srednekolymsk", name: "Russia Zone 10" },
    { tzid: "Asia/Kamchatka", name: "Russia Zone 11" },
    { tzid: "Asia/Anadyr", name: "Russia Zone 11" }
  ],
  "Rwanda": [{ tzid: "Africa/Maputo", name: "South Africa" }],
  "Serbia": [{ tzid: "Europe/Belgrade", name: "Central Europe" }],
  "Lithuania": [{ tzid: "Europe/Vilnius", name: "FLE" }],
  "Réunion": [{ tzid: "Indian/Reunion", name: "Mauritius" }],
  "Luxembourg": [{ tzid: "Europe/Luxembourg", name: "W. Europe" }],
  "Liberia": [{ tzid: "Africa/Monrovia", name: "Greenwich" }],
  "Romania": [{ tzid: "Europe/Bucharest", name: "GTB" }],
  "Tokelau": [{ tzid: "Pacific/Fakaofo", name: "Tonga" }],
  "Guinea-Bissau": [{ tzid: "Africa/Bissau", name: "Greenwich" }],
  "Guam": [{ tzid: "Pacific/Guam", name: "West Pacific" }],
  "Guatemala": [{ tzid: "America/Guatemala", name: "Central America" }],
  "Greece": [{ tzid: "Europe/Athens", name: "GTB" }],
  "Equatorial Guinea": [{ tzid: "Africa/Lagos", name: "W. Central Africa" }],
  "Guadeloupe": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "Bahrain": [{ tzid: "Asia/Qatar", name: "Arab" }],
  "Guyana": [{ tzid: "America/Guyana", name: "SA Western" }],
  "Guernsey": [{ tzid: "Europe/London", name: "GMT" }],
  "French Guiana": [{ tzid: "America/Cayenne", name: "SA Eastern" }],
  "Georgia": [{ tzid: "Asia/Tbilisi", name: "Georgian" }],
  "Grenada": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "Britain (UK)": [{ tzid: "Europe/London", name: "GMT" }],
  "Gabon": [{ tzid: "Africa/Lagos", name: "W. Central Africa" }],
  "Guinea": [{ tzid: "Africa/Abidjan", name: "Greenwich" }],
  "Gambia": [{ tzid: "Africa/Abidjan", name: "Greenwich" }],
  "Greenland": [
    { tzid: "America/Godthab", name: "Greenland" },
    { tzid: "America/Danmarkshavn", name: "UTC" },
    { tzid: "America/Scoresbysund", name: "Azores" },
    { tzid: "America/Thule", name: "Atlantic" }
  ],
  "Gibraltar": [{ tzid: "Europe/Gibraltar", name: "W. Europe" }],
  "Ghana": [{ tzid: "Africa/Accra", name: "Greenwich" }],
  "Oman": [{ tzid: "Asia/Dubai", name: "Arabian" }],
  "Botswana": [{ tzid: "Africa/Maputo", name: "South Africa" }],
  "Croatia": [{ tzid: "Europe/Belgrade", name: "Central Europe" }],
  "Haiti": [{ tzid: "America/Port-au-Prince", name: "Eastern" }],
  "Hungary": [{ tzid: "Europe/Budapest", name: "Central Europe" }],
  "Hong Kong": [{ tzid: "Asia/Hong_Kong", name: "China" }],
  "Honduras": [{ tzid: "America/Tegucigalpa", name: "Central America" }],
  "Latvia": [{ tzid: "Europe/Riga", name: "FLE" }],
  "Andorra": [{ tzid: "Europe/Andorra", name: "W. Europe" }],
  "Puerto Rico": [{ tzid: "America/Puerto_Rico", name: "SA Western" }],
  "Palestine": [{ tzid: "Asia/Gaza", name: "Palestine Time" }],
  "Palau": [{ tzid: "Pacific/Palau", name: "Tokyo" }],
  "Portugal": [
    { tzid: "Europe/Lisbon", name: "Lisbon" },
    { tzid: "Atlantic/Azores", name: "Azores" }
  ],
  "Korea (South)": [{ tzid: "Asia/Seoul", name: "Korea" }],
  "Paraguay": [{ tzid: "America/Asuncion", name: "Paraguay" }],
  "Iraq": [{ tzid: "Asia/Baghdad", name: "Arabic" }],
  "Panama": [{ tzid: "America/Panama", name: "SA Pacific" }],
  "French Polynesia": [{ tzid: "Pacific/Tahiti", name: "Hawaiian" }],
  "Papua New Guinea": [
    { tzid: "Pacific/Port_Moresby", name: "West Pacific" },
    { tzid: "Pacific/Bougainville", name: "Central Pacific" }
  ],
  "Peru": [{ tzid: "America/Lima", name: "SA Pacific" }],
  "Pakistan": [{ tzid: "Asia/Karachi", name: "Pakistan" }],
  "Philippines": [{ tzid: "Asia/Manila", name: "Singapore" }],
  "Pitcairn": [{ tzid: "Pacific/Pitcairn", name: "Pitcairn Time" }],
  "Poland": [{ tzid: "Europe/Warsaw", name: "Central European" }],
  "St Pierre & Miquelon": [{ tzid: "America/Miquelon", name: "Miquelon Time" }],
  "Zambia": [{ tzid: "Africa/Maputo", name: "South Africa" }],
  "Western Sahara": [{ tzid: "Africa/El_Aaiun", name: "Morocco" }],
  "Estonia": [{ tzid: "Europe/Tallinn", name: "FLE" }],
  "Egypt": [{ tzid: "Africa/Cairo", name: "Egypt" }],
  "South Africa": [{ tzid: "Africa/Johannesburg", name: "South Africa" }],
  "Ecuador": [
    { tzid: "America/Guayaquil", name: "SA Pacific" },
    { tzid: "Pacific/Galapagos", name: "Central America" }
  ],
  "Albania": [{ tzid: "Europe/Tirane", name: "Central Europe" }],
  "Angola": [{ tzid: "Africa/Lagos", name: "W. Central Africa" }],
  "Kazakhstan": [
    { tzid: "Asia/Almaty", name: "Almaty" },
    { tzid: "Asia/Aqtobe", name: "Aqtobe" },
    { tzid: "Asia/Aqtau", name: "Aqtau" }
  ],
  "Ethiopia": [{ tzid: "Africa/Nairobi", name: "E. Africa" }],
  "Somalia": [{ tzid: "Africa/Nairobi", name: "E. Africa" }],
  "Zimbabwe": [{ tzid: "Africa/Maputo", name: "South Africa" }],
  "Cayman Islands": [{ tzid: "America/Panama", name: "SA Pacific" }],
  "Spain": [
    { tzid: "Europe/Madrid", name: "Madrid" },
    { tzid: "Africa/Ceuta", name: "Ceuta" },
    { tzid: "Atlantic/Canary", name: "GMT" }
  ],
  "Eritrea": [{ tzid: "Africa/Nairobi", name: "E. Africa" }],
  "Montenegro": [{ tzid: "Europe/Belgrade", name: "Central Europe" }],
  "Moldova": [{ tzid: "Europe/Chisinau", name: "E. Europe" }],
  "Madagascar": [{ tzid: "Africa/Nairobi", name: "E. Africa" }],
  "St Martin (French)": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "Morocco": [{ tzid: "Africa/Casablanca", name: "Morocco" }],
  "Monaco": [{ tzid: "Europe/Monaco", name: "W. Europe" }],
  "Uzbekistan": [{ tzid: "Asia/Tashkent", name: "Tashkent" }],
  "Myanmar (Burma)": [{ tzid: "Asia/Rangoon", name: "Myanmar" }],
  "Mali": [{ tzid: "Africa/Abidjan", name: "Greenwich" }],
  "Macau": [{ tzid: "Asia/Macau", name: "China" }],
  "Mongolia": [
    { tzid: "Asia/Ulaanbaatar", name: "Ulaanbaatar" },
    { tzid: "Asia/Choibalsan", name: "Choibalsan" }
  ],
  "Marshall Islands": [
    { tzid: "Pacific/Majuro", name: "Majuro" },
    { tzid: "Pacific/Kwajalein", name: "Kwajalein" }
  ],
  "Macedonia": [{ tzid: "Europe/Belgrade", name: "Central Europe" }],
  "US minor outlying islands": [
    { tzid: "Pacific/Pago_Pago", name: "UTC-11" },
    { tzid: "Pacific/Wake", name: "UTC+12" },
    { tzid: "Pacific/Honolulu", name: "Hawaiian" }
  ],
  "Malta": [{ tzid: "Europe/Malta", name: "W. Europe" }],
  "Malawi": [{ tzid: "Africa/Maputo", name: "South Africa" }],
  "Maldives": [{ tzid: "Indian/Maldives", name: "West Asia" }],
  "Martinique": [{ tzid: "America/Martinique", name: "SA Western" }],
  "Northern Mariana Islands": [{ tzid: "Pacific/Guam", name: "West Pacific" }],
  "Montserrat": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "Mauritania": [{ tzid: "Africa/Abidjan", name: "Greenwich" }],
  "Australia": [
    { tzid: "Antarctica/Macquarie", name: "Central Pacific" },
    { tzid: "Australia/Hobart", name: "Eastern - Hobart" },
    { tzid: "Australia/Sydney", name: "Eastern - Sydney" },
    { tzid: "Australia/Brisbane", name: "Eastern - Brisbane" },
    { tzid: "Australia/Adelaide", name: "Central- Adelaide" },
    { tzid: "Australia/Darwin", name: "Central - Darwin" },
    { tzid: "Australia/Perth", name: "Western" }
  ],
  "Uganda": [{ tzid: "Africa/Nairobi", name: "E. Africa" }],
  "Malaysia": [{ tzid: "Asia/Kuala_Lumpur", name: "Kuala Lumpur" }],
  "Mexico": [
    { tzid: "America/Mexico_City", name: "Central - Mexico City" },
    { tzid: "America/Cancun", name: "Eastern" },
    { tzid: "America/Chihuahua", name: "Mountain - Chihuahua" },
    { tzid: "America/Hermosillo", name: "Mountain - Hermosillo" },
    { tzid: "America/Tijuana", name: "Pacific" }
  ],
  "Vanuatu": [{ tzid: "Pacific/Efate", name: "Central Pacific" }],
  "France": [{ tzid: "Europe/Paris", name: "Romance" }],
  "Aruba": [{ tzid: "America/Curacao", name: "SA Western" }],
  "St Helena": [{ tzid: "Africa/Abidjan", name: "Greenwich" }],
  "Afghanistan": [{ tzid: "Asia/Kabul", name: "Afghanistan" }],
  "Åland Islands": [{ tzid: "Europe/Helsinki", name: "FLE" }],
  "Finland": [{ tzid: "Europe/Helsinki", name: "FLE" }],
  "Fiji": [{ tzid: "Pacific/Fiji", name: "Fiji" }],
  "Falkland Islands": [{ tzid: "Atlantic/Stanley", name: "SA Eastern" }],
  "Micronesia": [{ tzid: "Pacific/Kosrae", name: "Central Pacific" }],
  "Faroe Islands": [{ tzid: "Atlantic/Faroe", name: "Faroe Time" }],
  "Nicaragua": [{ tzid: "America/Managua", name: "Central America" }],
  "Netherlands": [{ tzid: "Europe/Amsterdam", name: "W. Europe" }],
  "Norway": [{ tzid: "Europe/Oslo", name: "W. Europe" }],
  "Namibia": [{ tzid: "Africa/Windhoek", name: "Namibia" }],
  "New Caledonia": [{ tzid: "Pacific/Noumea", name: "Central Pacific" }],
  "Niger": [{ tzid: "Africa/Lagos", name: "W. Central Africa" }],
  "Norfolk Island": [{ tzid: "Pacific/Norfolk", name: "Central Pacific" }],
  "Nigeria": [{ tzid: "Africa/Lagos", name: "W. Central Africa" }],
  "New Zealand": [{ tzid: "Pacific/Auckland", name: "New Zealand" }],
  "Nepal": [{ tzid: "Asia/Kathmandu", name: "Nepal Time" }],
  "Nauru": [{ tzid: "Pacific/Nauru", name: "UTC+12" }],
  "Niue": [{ tzid: "Pacific/Niue", name: "UTC-11" }],
  "Cook Islands": [{ tzid: "Pacific/Rarotonga", name: "Hawaiian" }],
  "Côte d'Ivoire": [{ tzid: "Africa/Abidjan", name: "Greenwich" }],
  "Liechtenstein": [{ tzid: "Europe/Zurich", name: "W. Europe" }],
  "Colombia": [{ tzid: "America/Bogota", name: "SA Pacific" }],
  "China": [
    { tzid: "Asia/Shanghai", name: "China" },
    { tzid: "Asia/Urumqi", name: "Central Asia" }
  ],
  "Cameroon": [{ tzid: "Africa/Lagos", name: "W. Central Africa" }],
  "Chile": [
    { tzid: "America/Santiago", name: "Santiago" },
    { tzid: "Pacific/Easter", name: "Easter Island" }
  ],
  "Cocos (Keeling) Islands": [{ tzid: "Indian/Cocos", name: "Myanmar" }],
  "Canada": [
    { tzid: "America/St_Johns", name: "Newfoundland" },
    { tzid: "America/Halifax", name: "Atlantic - Halifax" },
    { tzid: "America/Toronto", name: "Eastern - Toronto" },
    { tzid: "America/Iqaluit", name: "Eastern - Iqaluit" },
    { tzid: "America/Winnipeg", name: "Central - Winnipeg" },
    { tzid: "America/Regina", name: "Central - Regina" },
    { tzid: "America/Edmonton", name: "Mountain - Edmonton" },
    { tzid: "America/Yellowknife", name: "Mountain - Yellowknife" },
    { tzid: "America/Dawson_Creek", name: "Dawson Creek" },
    { tzid: "America/Vancouver", name: "Pacific - Vancouver" },
    { tzid: "America/Whitehorse", name: "Pacific - Whitehorse" }
  ],
  "Congo (Rep.)": [{ tzid: "Africa/Lagos", name: "W. Central Africa" }],
  "Central African Rep": [{ tzid: "Africa/Lagos", name: "W. Central Africa" }],
  "Congo (Dem. Rep.)": [
    { tzid: "Africa/Maputo", name: "South Africa" },
    { tzid: "Africa/Lagos", name: "W. Central Africa" }
  ],
  "Czech Republic": [{ tzid: "Europe/Prague", name: "Central Europe" }],
  "Cyprus": [{ tzid: "Asia/Nicosia", name: "GTB" }],
  "Christmas Island": [{ tzid: "Indian/Christmas", name: "SE Asia" }],
  "Costa Rica": [{ tzid: "America/Costa_Rica", name: "Central America" }],
  "Curacao": [{ tzid: "America/Curacao", name: "SA Western" }],
  "Cape Verde": [{ tzid: "Atlantic/Cape_Verde", name: "Cape Verde" }],
  "Cuba": [{ tzid: "America/Havana", name: "Eastern" }],
  "Swaziland": [{ tzid: "Africa/Johannesburg", name: "South Africa" }],
  "Syria": [{ tzid: "Asia/Damascus", name: "Syria" }],
  "St Maarten (Dutch)": [{ tzid: "America/Curacao", name: "SA Western" }],
  "Kyrgyzstan": [{ tzid: "Asia/Bishkek", name: "Central Asia" }],
  "Kenya": [{ tzid: "Africa/Nairobi", name: "E. Africa" }],
  "South Sudan": [{ tzid: "Africa/Khartoum", name: "E. Africa" }],
  "Suriname": [{ tzid: "America/Paramaribo", name: "SA Eastern" }],
  "Kiribati": [
    { tzid: "Pacific/Tarawa", name: "UTC+12" },
    { tzid: "Pacific/Enderbury", name: "Tonga" },
    { tzid: "Pacific/Kiritimati", name: "Line Islands" }
  ],
  "Cambodia": [{ tzid: "Asia/Bangkok", name: "SE Asia" }],
  "El Salvador": [{ tzid: "America/El_Salvador", name: "Central America" }],
  "Comoros": [{ tzid: "Africa/Nairobi", name: "E. Africa" }],
  "Sao Tome & Principe": [{ tzid: "Africa/Abidjan", name: "Greenwich" }],
  "Slovakia": [{ tzid: "Europe/Prague", name: "Central Europe" }],
  "Svalbard & Jan Mayen": [{ tzid: "Europe/Oslo", name: "W. Europe" }],
  "Slovenia": [{ tzid: "Europe/Belgrade", name: "Central Europe" }],
  "Korea (North)": [{ tzid: "Asia/Pyongyang", name: "North Korea" }],
  "Kuwait": [{ tzid: "Asia/Riyadh", name: "Arab" }],
  "Senegal": [{ tzid: "Africa/Abidjan", name: "Greenwich" }],
  "San Marino": [{ tzid: "Europe/Rome", name: "W. Europe" }],
  "Sierra Leone": [{ tzid: "Africa/Abidjan", name: "Greenwich" }],
  "Seychelles": [{ tzid: "Indian/Mahe", name: "Mauritius" }],
  "Solomon Islands": [{ tzid: "Pacific/Guadalcanal", name: "Central Pacific" }],
  "Saudi Arabia": [{ tzid: "Asia/Riyadh", name: "Arab" }],
  "Singapore": [{ tzid: "Asia/Singapore", name: "Singapore" }],
  "Sweden": [{ tzid: "Europe/Stockholm", name: "W. Europe" }],
  "Sudan": [{ tzid: "Africa/Khartoum", name: "E. Africa" }],
  "Dominican Republic": [{ tzid: "America/Santo_Domingo", name: "SA Western" }],
  "Dominica": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "Djibouti": [{ tzid: "Africa/Nairobi", name: "E. Africa" }],
  "Denmark": [{ tzid: "Europe/Copenhagen", name: "Romance" }],
  "Germany": [{ tzid: "Europe/Berlin", name: "Berlin" }],
  "Yemen": [{ tzid: "Asia/Riyadh", name: "Arab" }],
  "Austria": [{ tzid: "Europe/Vienna", name: "W. Europe" }],
  "Algeria": [{ tzid: "Africa/Algiers", name: "W. Central Africa" }],
  "United States": [
    { tzid: "America/New_York", name: "Eastern" },
    { tzid: "America/Chicago", name: "Central" },
    { tzid: "America/Denver", name: "Mountain" },
    { tzid: "America/Phoenix", name: "Mountain - AZ" },
    { tzid: "America/Los_Angeles", name: "Pacific" },
    { tzid: "America/Anchorage", name: "Alaskan" },
    { tzid: "Pacific/Honolulu", name: "Hawaiian" }
  ],
  "Uruguay": [{ tzid: "America/Montevideo", name: "Montevideo" }],
  "Mayotte": [{ tzid: "Africa/Nairobi", name: "E. Africa" }],
  "Mauritius": [{ tzid: "Indian/Mauritius", name: "Mauritius" }],
  "St Kitts & Nevis": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "Lebanon": [{ tzid: "Asia/Beirut", name: "Middle East" }],
  "St Lucia": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "Laos": [{ tzid: "Asia/Bangkok", name: "SE Asia" }],
  "Tuvalu": [{ tzid: "Pacific/Funafuti", name: "UTC+12" }],
  "Taiwan": [{ tzid: "Asia/Taipei", name: "Taipei" }],
  "Trinidad & Tobago": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "Turkey": [{ tzid: "Europe/Istanbul", name: "Turkey" }],
  "Sri Lanka": [{ tzid: "Asia/Colombo", name: "Sri Lanka" }],
  "Switzerland": [{ tzid: "Europe/Zurich", name: "W. Europe" }],
  "Tunisia": [{ tzid: "Africa/Tunis", name: "W. Central Africa" }],
  "Tonga": [{ tzid: "Pacific/Tongatapu", name: "Tonga" }],
  "East Timor": [{ tzid: "Asia/Dili", name: "Tokyo" }],
  "Turkmenistan": [{ tzid: "Asia/Ashgabat", name: "West Asia" }],
  "Tajikistan": [{ tzid: "Asia/Dushanbe", name: "West Asia" }],
  "Lesotho": [{ tzid: "Africa/Johannesburg", name: "South Africa" }],
  "Thailand": [{ tzid: "Asia/Bangkok", name: "SE Asia" }],
  "Togo": [{ tzid: "Africa/Abidjan", name: "Greenwich" }],
  "Chad": [{ tzid: "Africa/Ndjamena", name: "W. Central Africa" }],
  "Turks & Caicos Is": [{ tzid: "America/Grand_Turk", name: "SA Western" }],
  "Libya": [{ tzid: "Africa/Tripoli", name: "Libya" }],
  "Vatican City": [{ tzid: "Europe/Rome", name: "W. Europe" }],
  "St Vincent": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "United Arab Emirates": [{ tzid: "Asia/Dubai", name: "Arabian" }],
  "Venezuela": [{ tzid: "America/Caracas", name: "Venezuela" }],
  "Antigua & Barbuda": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "Virgin Islands (UK)": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "Anguilla": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "Virgin Islands (US)": [{ tzid: "America/Port_of_Spain", name: "SA Western" }],
  "Iceland": [{ tzid: "Atlantic/Reykjavik", name: "Greenwich" }],
  "Iran": [{ tzid: "Asia/Tehran", name: "Iran" }],
  "Armenia": [{ tzid: "Asia/Yerevan", name: "Caucasus" }],
  "Italy": [{ tzid: "Europe/Rome", name: "W. Europe" }],
  "Vietnam": [{ tzid: "Asia/Bangkok", name: "SE Asia" }],
  "Samoa (American)": [{ tzid: "Pacific/Pago_Pago", name: "UTC-11" }],
  "Argentina": [{ tzid: "America/Argentina/Salta", name: "Argentina" }],
  "Isle of Man": [{ tzid: "Europe/London", name: "GMT" }],
  "Israel": [{ tzid: "Asia/Jerusalem", name: "Israel" }],
  "British Indian Ocean Territory": [{ tzid: "Indian/Chagos", name: "Central Asia" }],
  "India": [{ tzid: "Asia/Kolkata", name: "India" }],
  "Tanzania": [{ tzid: "Africa/Nairobi", name: "E. Africa" }],
  "Azerbaijan": [{ tzid: "Asia/Baku", name: "Azerbaijan" }],
  "Ireland": [{ tzid: "Europe/Dublin", name: "GMT" }],
  "Indonesia": [
    { tzid: "Asia/Jakarta", name: "Jakarta" },
    { tzid: "Asia/Makassar", name: "Singapore" },
    { tzid: "Asia/Jayapura", name: "Tokyo" }
  ],
  "Ukraine": [{ tzid: "Europe/Kiev", name: "Kiev" }],
  "Qatar": [{ tzid: "Asia/Qatar", name: "Arab" }],
  "Mozambique": [{ tzid: "Africa/Maputo", name: "South Africa" }]
};

function onCountryChange() {
  $("#eventsCalTimezone").empty();
  var countryCode = $("#eventsCalCountry").val();

  document.getElementById('countrycode').value = countryCode;

  for (var i in timezone_json[countryCode]) {
    var timezoneObj = timezone_json[countryCode][i];
    var now = moment(new Date());
    $("#eventsCalTimezone").append(
      "<option value='" +
      "(UTC" +
      moment.tz(now, timezoneObj.tzid).format("Z") +
      ") " +
      timezoneObj.name  +
        "'>" +
        "(UTC" +
        moment.tz(now, timezoneObj.tzid).format("Z") +
        ") " +
        timezoneObj.name 
    );
  }
}

$(document).ready(function () {
  $("#eventsCalCountry").change(onCountryChange);
  $("#eventsCalCountry").val("United States");
  onCountryChange();
});
